spring.application.name=AgendaCurso
spring.datasource.url=jdbc:sqlserver://Pc:1433;databaseName=AgendaCurso;trustServerCertificate=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.datasource.username=neto
spring.datasource.password=neto0902
spring.jpa.hibernate.ddl-auto=update
