CREATE TABLE Curso(
	IdCurso INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(200) NOT NULL

	CONSTRAINT Pk_Curso PRIMARY KEY(IdCurso)
)



CREATE TABLE Aluno(
	IdAluno INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(250) NOT NULL,
	Matricula VARCHAR(11) NOT NULL,
	Email VARCHAR(250),
	Senha VARCHAR(50),
	IdRole INT NOT NULL,
	IdCurso INT,
	
	CONSTRAINT PK_Aluno PRIMARY KEY (IdAluno),
	CONSTRAINT UQ_Matricula UNIQUE (Matricula),
	CONSTRAINT FK_Aluno_Curso FOREIGN KEY (IdCurso) REFERENCES Curso(IdCurso)
)

CREATE TABLE Agenda(
	IdAluno INT NOT NULL,

	CONSTRAINT PK_Agenda PRIMARY KEY (IdAluno),
	CONSTRAINT FK_Agenda_Aluno FOREIGN KEY (IdAluno) REFERENCES Aluno(IdAluno)
)